repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-added-large-files
        files: ^ai-backend/
      - id: check-toml
        files: ^ai-backend/
      - id: check-yaml
        files: ^ai-backend/
      - id: end-of-file-fixer
        files: ^ai-backend/
      - id: trailing-whitespace
        files: ^ai-backend/

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.11.7
    hooks:
      - id: ruff
        args: [--fix]
        files: ^ai-backend/
      - id: ruff-format
        files: ^ai-backend/

  - repo: local
    hooks:
      - id: playground-eslint
        name: Run ESLint
        language: system
        files: ^playground/
        entry: bash -c 'cd playground && bun run lint'

  - repo: local
    hooks:
      - id: playground-prettier
        name: Run Prettier
        language: system
        files: ^playground/
        entry: bash -c 'cd playground && bun run format'
