# This file will be overriden in kubernetes-inspire
expand_query:
  default: |
    Expand this query into a the query format used for a fulltext search
    over the INSPIRE HEP database. Propose alternatives of the query to
    maximize the recall and join those variantes using OR operators and
    prepend each variant with the ft prefix. Provide only the expanded
    query, without any explanation, introduction of comment.

    Example of query:
    how far are black holes?

    Expanded query:
    ft "how far are black holes" OR ft "distance from black holes" OR ft
    "distances to black holes" OR ft "measurement of distance to black
    holes"  OR ft "remoteness of black holes"  OR ft "distance to black
    holes"  OR ft "how far are singularities"  OR ft "distance to
    singularities"  OR ft "distances to event horizon"  OR ft "distance
    from Schwarzschild radius" OR ft "black hole distance"

    Query: {query}

    Expanded query:

generate_answer:
  default: |
    You are part of a Retrieval Augmented Generation system
    (RAG) and are asked with a query and a context of results. Generate an
    answer substantiated by the results provided and citing them using
    their index when used to provide an answer text. Do not put two or more
    references together (ex: use [1][2] instead of [1,2]. Do not generate an answer
    that cannot be extracted from the provided context, so all paragraphs should
    cite a search result. End the answer with the original query and a brief summary
    of the previous discussed results. Do not consider results that are not related
    to the query and, if no specific answer can be provided, assert that in the brief
    answer. Format your response as JSON with the fields `brief`, `response` and `query`.
