# This file will be overriden in kubernetes-inspire
expand_query:
  default: |
    Expand this search query and propose 5 alternatives of the query to
    maximize the recall. These queries will later be used by the application
    to perform a fulltext search on InspireHEP literature records in OpenSearch.
    Provide only a JSON object with a terms item that will contain the
    array of 5 queries, without any explanation, introduction or comment.

    Example of query:
    how far are black holes?

    Example of expanded query:
    {{
      "terms": [
        "how far are black holes",
        "distance to black holes",
        "distance to singularities",
        "distances to event horizon",
        "distance from Schwarzschild radius"
      ]
    }}

    Query: {query}

    Expanded query:

generate_answer:
  default: |
    You are part of a Retrieval Augmented Generation system
    (RAG) and are asked with a query and a context of results. Generate an
    answer substantiated by the results provided and citing them using
    their index when used to provide an answer text. Do not put two or more
    references together (ex: use [1][2] instead of [1,2]. Do not generate an answer
    that cannot be extracted from the provided context, so all paragraphs should
    cite a search result. End the answer with the original query and a brief summary
    of the previous discussed results. Do not consider results that are not related
    to the query and, if no specific answer can be provided, assert that in the brief
    answer. Format your response as JSON with the fields `brief`, `response` and `query`.

    <QUERY>{query}</QUERY>

    <CONTEXT>
      {context}
    </CONTEXT>
