"""Initial migration

Revision ID: 9d0b2efe625a
Revises:
Create Date: 2025-01-31 15:48:38.305077

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "9d0b2efe625a"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "queries_ir",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("query", sa.String(), nullable=False),
        sa.Column("brief", sa.String(), nullable=False),
        sa.Column("response", sa.String(), nullable=False),
        sa.Column("references", sa.ARRAY(sa.String()), nullable=False),
        sa.Column("expanded_query", sa.String(), nullable=False),
        sa.Column("model", sa.String(), nullable=False),
        sa.Column("backend_version", sa.String(), nullable=True),
        sa.Column("matomo_client_id", sa.Uuid(), nullable=True),
        sa.Column("user", sa.String(), nullable=False),
        sa.Column(
            "timestamp", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("response_time", sa.Float(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_queries_ir_timestamp", "queries_ir", ["timestamp"], unique=False
    )
    op.create_table(
        "feedback",
        sa.Column("query_id", sa.Uuid(), nullable=False),
        sa.Column("rating", sa.Boolean(), nullable=False),
        sa.Column("comment", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(
            ["query_id"],
            ["queries_ir.id"],
        ),
        sa.PrimaryKeyConstraint("query_id"),
    )
    op.create_index("idx_feedback_rating", "feedback", ["rating"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("idx_feedback_rating", table_name="feedback")
    op.drop_table("feedback")
    op.drop_index("idx_queries_ir_timestamp", table_name="queries_ir")
    op.drop_table("queries_ir")
    # ### end Alembic commands ###
