"""Make user optional

Revision ID: fb7c57a4daeb
Revises: 9d0b2efe625a
Create Date: 2025-02-03 14:01:38.595544

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "fb7c57a4daeb"
down_revision: Union[str, None] = "9d0b2efe625a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("queries_ir", "user", existing_type=sa.VARCHAR(), nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("queries_ir", "user", existing_type=sa.VARCHAR(), nullable=False)
    # ### end Alembic commands ###
