name: INSPIRE-AI

services:
  backend:
    build:
      dockerfile: Dockerfile
      target: dev
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - LLM_API_BASE=http://194.12.189.112:11434
    volumes:
      - ./src:/app/src
      - ./tests:/app/tests
