name: INSPIRE-AI

services:
  backend:
    build:
      dockerfile: Dockerfile
      target: dev
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./src:/app/src
      - ./tests:/app/tests
